baseURL = 'https://Qian-Donglin.github.io/site/'
languageCode = 'ja'
title = 'Sen(Qian)のメモ'
disablePathToLower = true
enableGitInfo = true
theme = "hugo-book"
# publishDir = "docs"
# canonifyurls = true
BookSearch = true
[params]
	BookTheme = 'auto'
	BookToC = true
	BookRepo = 'https://github.com/Qian-Donglin/site'
	BookCommitPath = 'commit'
	BookSearch = true
	BookComments = true
	BookPortableLinks = true
